name = input("What is your name? ")
favmovie = input("What is your favorite movie? ")
favsnack = input("What is your favorite snack? ")
print("Hello",name,"Here is what I know about you.")
print("Favorite movie:",favmovie)
print("Favorite snack:",favsnack)